// GRIDA Icons — 프롬프트 데이터 (75종, 실물 이미지 전수 검증 기준)
// file: 해당 주제를 '실제로' 그린 이미지 파일 (원본 파일명 셔플 보정 완료)
window.GRIDA_DATA = {
  CORE_MJ: ", solid flat fills, two-tone color blocking, chunky rounded blob shapes, fully rounded line caps, small details cut out as thick light-gray #EBEBEB rounded strokes, minimal flat icon set style, isolated on pure white background, centered, fills the frame --ar 1:1 --style raw --s 50 --no outline, gradient, shadow, 3d, texture, text, watermark",
  CORE_HF: ", drawn as a simple flat vector icon: solid flat fills only, two or three colors, chunky rounded blob shapes with fully rounded line caps, small details cut out as thick light-gray rounded strokes, absolutely no outlines, no gradients, no shadows, no 3D, pure white empty background, subject centered and filling the frame",
  SETS: [
    {
      id: "fruit", name: "Fruit", color: "#E94B35",
      items: [
        { ko: "사과", en: "apple", file: "apple.png", body: "flat vector icon of a red #E94B35 apple, round body with two bottom lobes, curved lime green #8BC02F stem on top, two light gray #EBEBEB curved bracket-shaped shine marks facing each other at center" },
        { ko: "바나나", en: "banana", file: "banana.png", body: "flat vector icon of a yellow #F2C500 banana curving diagonally from lower-left to upper-right, tilted 45 degrees, with a lime green #8BC02F rounded stem cap on the upper-right tip" },
        { ko: "블루베리", en: "blueberry", file: "blueberry.png", body: "flat vector icon of two overlapping blueberries, larger deep purple #6D2AB0 berry left and purple #9C56B8 berry right, each with one small light gray #EBEBEB dot highlight, backed by a deep green #42A141 leaf and lime green #8BC02F leaf with light gray midrib strokes" },
        { ko: "체리", en: "cherry", file: "cherry.png", body: "flat vector icon of two round cherries side by side, dark red #C23824 on the left overlapped by red #E94B35 on the right, two long curved lime green #8BC02F stems sweeping up to meet at top right" },
        { ko: "초콜릿", en: "chocolate", file: "chocolate.png", body: "flat vector icon of a tan #BF9760 cacao pod, oval silhouette tilted 45 degrees, with a brown #8D5836 pointed lens-shaped stripe spanning the middle lengthwise and a short curved brown #8D5836 stem at the top right" },
        { ko: "시트러스", en: "citrus", file: "citrus.png", body: "flat vector icon of a cut citrus half seen face-on, yellow #F2C500 outer ring and small center circle, six pie-wedge segments alternating orange #F59D00 and light gray #EBEBEB around the center" },
        { ko: "코코넛", en: "coconut", file: "coconut.png", body: "flat vector icon of a whole tan #BF9760 coconut, plain round silhouette slightly taller than wide, with three small brown #8D5836 dots clustered near the upper right" },
        { ko: "두리안", en: "durian", file: "durian.png", body: "flat vector icon of a yellow #F2C500 durian, round silhouette ringed with many blunt spikes, short curved lime green #8BC02F stem on top, four orange #F59D00 curved arc marks scattered on the body" },
        { ko: "포도", en: "grape", file: "grape.png", body: "flat vector icon of a grape cluster of six circles in a 3-2-1 stack, mixing deep purple #6D2AB0, purple #9C56B8, and two light gray #EBEBEB berries, topped by a curved lime green #8BC02F stem" },
        { ko: "키위", en: "kiwi", file: "kiwi.png", body: "flat vector icon of a kiwi slice, light gray #EBEBEB circular face offset over a lime green #8BC02F body showing at lower-left like a cylinder, center holds a lime green #8BC02F circle with six radiating spokes forming an asterisk wheel" },
        { ko: "레몬", en: "lemon", file: "lemon.png", body: "flat vector icon of a citrus half-slice wedge tilted 45 degrees, light gray #EBEBEB rind crescent behind, four fan segments radiating from one corner alternating yellow #F2C500 and orange #F59D00" },
        { ko: "리치", en: "lychee", file: "lychee.png", body: "flat vector icon of a lychee, red #E94B35 lower hemisphere beneath a light gray #EBEBEB dome top, with six short dark red #C23824 spike strokes sticking out around the red lower half" },
        { ko: "망고", en: "mango", file: "mango.png", body: "flat vector icon of a yellow #F2C500 mango, plump kidney silhouette tilted 45 degrees with the tip pointing lower-left, short curved lime green #8BC02F stem at the upper right" },
        { ko: "망고스틴", en: "mangosteen", file: "mangosteen.png", body: "flat vector icon of a cut mangosteen, purple #9C56B8 rind forming the entire lower hemisphere, light gray #EBEBEB upper half of flesh with one pointed mid gray #BEBEBE petal-shaped segment rising at the center top" },
        { ko: "멜론", en: "melon", file: "melon.png", body: "flat vector icon of a melon wedge, crescent tilted 45 degrees with yellow #F2C500 rind and light gray #EBEBEB inner flesh, three small yellow #F2C500 seed dashes in a diagonal row on the flesh" },
        { ko: "오렌지", en: "orange", file: "orange.png", body: "flat vector icon of a whole round yellow #F2C500 orange, short curved lime green #8BC02F stem on top, three short orange #F59D00 diagonal dash marks grouped on the lower right of the body" },
        { ko: "파파야", en: "papaya", file: "papaya.png", body: "flat vector icon of a papaya half, yellow #F2C500 rounded teardrop silhouette tilted 45 degrees, large light gray #EBEBEB inner cavity holding four dark gray #323232 rounded seed dashes" },
        { ko: "복숭아", en: "peach", file: "peach.png", body: "flat vector icon of a red #E94B35 peach shaped like a rounded heart with a pointed top, a short dark red #C23824 crease stroke near the bottom, resting on two wide lime green #8BC02F leaves spreading left and right" },
        { ko: "배", en: "pear", file: "pear.png", body: "flat vector icon of a yellow #F2C500 pear, two-lobed gourd silhouette with small upper bulb and large lower bulb, tilted 45 degrees toward lower-left, curved lime green #8BC02F stem at the top right" },
        { ko: "파인애플", en: "pineapple", file: "pineapple.png", body: "flat vector icon of a yellow #F2C500 oval pineapple body tilted 45 degrees, spiky lime green #8BC02F three-pointed crown at the upper right, seven light gray #EBEBEB short rounded dashes arranged in a grid across the body" },
        { ko: "석류", en: "pomegranate", file: "pomegranate.png", body: "flat vector icon of a red #E94B35 pomegranate, round body with a jagged pointed crown calyx at the upper right, large light gray #EBEBEB circular cut face filled with seven dark gray #323232 rounded seed dashes" },
        { ko: "스타프루트", en: "starfruit", file: "starfruit.png", body: "flat vector icon of a yellow #F2C500 five-pointed star with rounded tips and soft concave edges, a light gray #EBEBEB five-stroke asterisk mark radiating from the center" },
        { ko: "딸기", en: "strawberry", file: "strawberry.png", body: "flat vector icon of a red #E94B35 strawberry, broad rounded top tapering to a rounded bottom, three lime green #8BC02F pointed leaves fanned across the top, seven light gray #EBEBEB oval seed dots over the body" },
        { ko: "수박 조각", en: "watermelon slice", file: "watermelon-slice.png", body: "flat vector icon of a watermelon quarter wedge tilted 45 degrees, red #E94B35 flesh inside a thick lime green #8BC02F rind arc along the outer curve, three dark gray #323232 seed dashes in a diagonal line on the flesh" },
        { ko: "수박", en: "watermelon", file: "watermelon.png", body: "flat vector icon of a whole watermelon, lime green #8BC02F oval ball crossed by wide deep green #42A141 wavy irregular stripes flowing diagonally across the surface" }
      ]
    },
    {
      id: "herb", name: "Herb", color: "#8BC02F",
      items: [
        { ko: "팔각", en: "anise", file: "anise.png", body: "flat vector icon of star anise flower, four large brown #8D5836 pointed petals in a cross plus tan #BF9760 diagonal petals behind, round tan #BF9760 center circle" },
        { ko: "바질", en: "basil", file: "herb.png", body: "flat vector icon of upright basil sprig, one large lime green #8BC02F ovate leaf on top and two side leaves, vertical deep green #42A141 stem with downward arrow-like branch strokes" },
        { ko: "후추 그라인더", en: "black pepper", file: "black-pepper.png", body: "flat vector icon of pepper mill tilted 45 degrees, light gray #EBEBEB body, dark gray #323232 head cap with light gray knob behind, dark gray band at lower end, five light gray dots sprinkling toward bottom-left" },
        { ko: "고추", en: "chili", file: "chili.png", body: "flat vector icon of red #E94B35 chili pepper, curved tapered body pointing to bottom-left tip, wavy lime green #8BC02F cap draped over top with short curved stem at upper right" },
        { ko: "시나몬", en: "cinnamon", file: "cinnamon.png", body: "flat vector icon of cinnamon stick lying diagonally, tan #BF9760 rounded roll, two brown #8D5836 diagonal dash strokes on the surface, white spiral swirl cross-section at the lower-left end" },
        { ko: "정향", en: "clove", file: "clove.png", body: "flat vector icon of clove bud, round tan #BF9760 head with thick tan stick shaft pointing to bottom-left, irregular brown #8D5836 blob wrapped diagonally across the head" },
        { ko: "냄비(허브)", en: "cooking pot", file: "cooking-pot.png", body: "flat vector icon of light gray #EBEBEB pot, dark gray #323232 rim bar with rounded handles on both sides, yellow #F2C500 liquid dripping over the rim in two drips, yellow zigzag steam swirl line above" },
        { ko: "고수", en: "coriander", file: "coriander.png", body: "flat vector icon of cilantro leaf, lime green #8BC02F fan-shaped leaf with three rounded scalloped lobes, straight deep green #42A141 stem stroke running diagonally to bottom-left corner" },
        { ko: "새싹 채소", en: "cress", file: "cress.png", body: "flat vector icon of sprouting seedling, two deep green #42A141 curved stem strokes forming a V, each tipped with a lime green #8BC02F pointed oval leaf spreading left and right" },
        { ko: "딜", en: "dill", file: "dill.png", body: "flat vector icon of dill twig drawn only in lime green #8BC02F rounded strokes, tall curved central stalk with three tiers of side branches, each branch ending in short forked spike strokes" },
        { ko: "마늘", en: "garlic", file: "onion.png", body: "flat vector icon of garlic bulb, purple #9C56B8 round bulb with short neck on top, large light gray #EBEBEB flame-shaped flesh inside, single purple teardrop clove at the center" },
        { ko: "생강", en: "ginger", file: "ginger.png", body: "flat vector icon of ginger root, yellow #F2C500 lumpy X-shaped rhizome with rounded knobby arms, four short orange #F59D00 curved dash marks scattered on the surface" },
        { ko: "대파", en: "green onion", file: "green-onion.png", body: "flat vector icon of spring onion, plump yellow #F2C500 bulb below, three lime green #8BC02F shoots on top, center shoot straight and the two outer shoots curving outward" },
        { ko: "허브 잎", en: "herb", file: "basil.png", body: "flat vector icon of generic herb leaf, single lime green #8BC02F three-lobed pointed leaf, long deep green #42A141 stem curving to bottom-left with a forked side shoot and vein strokes inside the leaf" },
        { ko: "민트", en: "mint", file: "mint.png", body: "flat vector icon of mint leaf, broad lime green #8BC02F leaf with jagged serrated edges tilted diagonally, deep green #42A141 midrib stroke from lower-left with three short side vein strokes" },
        { ko: "맵기 금지", en: "no chili", file: "no-chili.png", body: "flat vector icon of red #E94B35 curved chili with wavy lime green #8BC02F cap and stem, crossed out by a thick dark gray #323232 diagonal slash stroke from top-left to bottom-right" },
        { ko: "양파 슬라이스", en: "onion slice", file: "onion-slice.png", body: "flat vector icon of halved onion lying sideways, purple #9C56B8 rounded cone body pointing left with small nub tip, circular cut face on the right showing light gray #EBEBEB ring and purple ellipse center" },
        { ko: "양파", en: "onion", file: "garlic.png", body: "flat vector icon of yellow #F2C500 onion bulb, plump round body with small pointed knob on top, light gray #EBEBEB curved root whiskers forking from the bottom center" },
        { ko: "후추통", en: "pepper", file: "pepper.png", body: "flat vector icon of upright pepper shaker, small light gray #EBEBEB knob on top, large dark gray #323232 rounded cap, straight light gray body flaring slightly, dark gray base band" },
        { ko: "향신료 가루", en: "powder", file: "powder.png", body: "flat vector icon of spice powder spoon, dark gray #323232 horizontal spoon with oval bowl on the left and long handle right, three light gray #EBEBEB dots falling onto a light gray powder mound below" },
        { ko: "호박", en: "pumpkin", file: "pumpkin.png", body: "flat vector icon of squat pumpkin, tall yellow #F2C500 oval center lobe flanked by two rounded orange #F59D00 side lobes, thin curved yellow stem rising from the top" },
        { ko: "소금", en: "salt", file: "salt.png", body: "flat vector icon of upright salt shaker, dark gray #323232 dome cap on top, light gray #EBEBEB concave waisted middle band, wide flared dark gray bottom" },
        { ko: "소스", en: "sauce", file: "sauce.png", body: "flat vector icon of upright sauce bottle, light gray #EBEBEB nozzle tip and shoulder, dark gray #323232 body with a wide light gray horizontal label band across the middle" },
        { ko: "설탕", en: "sugar", file: "sugar.png", body: "flat vector icon of sugar pourer tilted 45 degrees, light gray #EBEBEB rounded body at upper right, dark gray #323232 diagonal band, light gray dome cap at lower left, five light gray grains scattered below" },
        { ko: "타마린드", en: "tamarind", file: "tamarind.png", body: "flat vector icon of tamarind pod, tan #BF9760 curved pod made of four overlapping round bumps arranged diagonally, short brown #8D5836 curved stem at the top-right end" }
      ]
    },
    {
      id: "food", name: "Food", color: "#05A9E3",
      items: [
        { ko: "앞치마", en: "apron", file: "spatula.png", body: "flat vector icon of a cyan blue #05A9E3 kitchen apron, front view, with a rounded light gray #EBEBEB bib top, light gray center pocket, and light gray #EBEBEB waist strings curling out from both sides" },
        { ko: "버거", en: "burger", file: "refrigerator.png", body: "flat vector icon of a burger, front view, yellow #F2C500 top and bottom buns, three light gray #EBEBEB sesame dashes on top, a wavy lime green #8BC02F lettuce stripe, and a straight red #E94B35 tomato stripe between the buns" },
        { ko: "샴페인", en: "champagne", file: "sign.png", body: "flat vector icon of a champagne bottle tilted diagonally, neck pointing upper right, light gray #EBEBEB glass body, cyan blue #05A9E3 diamond-shaped foil cap, and a cyan blue #05A9E3 diamond label on the body" },
        { ko: "셰프 모자", en: "chef hat", file: "pot.png", body: "flat vector icon of a cyan blue #05A9E3 chef hat, front view, three puffy cloud lobes on top, light gray #EBEBEB band at the base, and three light gray crease marks: one straight center stroke flanked by two curved strokes" },
        { ko: "클로슈 접시", en: "dish", file: "take-away.png", body: "flat vector icon of a covered dish, light gray #EBEBEB cloche dome with a mid gray #BEBEBE knob, resting on a cyan blue #05A9E3 rounded tray base, with two wavy cyan blue #05A9E3 steam squiggles rising above left and right" },
        { ko: "도넛", en: "donuts", file: "champagne.png", body: "flat vector icon of a round donut, front view, orange #F59D00 icing covering the top half with a wavy drip edge, yellow #F2C500 lower half, white center hole, and three light gray #EBEBEB sprinkle dashes on the icing" },
        { ko: "음식 배달", en: "food delivery", file: "menu-book.png", body: "flat vector icon of a rushing covered dish, light gray #EBEBEB cloche dome with mid gray #BEBEBE knob on a cyan blue #05A9E3 rounded tray, with three cyan blue #05A9E3 horizontal speed lines of decreasing length on the left" },
        { ko: "음식 주문", en: "food order", file: "onigiri.png", body: "flat vector icon of a phone food order: large light gray #EBEBEB curved telephone handset spanning the frame diagonally, with a small cyan blue #05A9E3 cloche dish on a tray in the upper right corner" },
        { ko: "메뉴북", en: "menu book", file: "pizza-delivery.png", body: "flat vector icon of a menu book, upright lime green #8BC02F cover with a deep green #42A141 band across the bottom third, a white cloche-on-tray emblem centered on the cover, and two deep green #42A141 ring tabs on the left edge" },
        { ko: "메뉴 리스트", en: "menu list", file: "rice-bowl.png", body: "flat vector icon of a folded menu card standing upright, cover split into a deep green #42A141 left panel and lime green #8BC02F right panel, with a mid gray #BEBEBE inner page slanting up behind the top edge" },
        { ko: "주먹밥", en: "onigiri", file: "table.png", body: "flat vector icon of an onigiri rice ball, rounded light gray #EBEBEB triangle, six mid gray #BEBEBE diagonal rice dashes across the face, and a cyan blue #05A9E3 rounded rectangular nori band at the bottom center" },
        { ko: "팬케이크", en: "pancake", file: "pancake.png", body: "flat vector icon of a pancake stack: three layers alternating tan #BF9760 and brown #8D5836, yellow #F2C500 syrup dripping over the top with long drips, an orange #F59D00 round butter pat on top, and a mid gray #BEBEBE plate bar underneath" },
        { ko: "피자 커터", en: "pizza cutter", file: "pudding.png", body: "flat vector icon of a pizza cutter tilted diagonally, thick lime green #8BC02F handle pointing lower left with a forked yoke, round light gray #EBEBEB blade in the upper right with a mid gray #BEBEBE center hub" },
        { ko: "피자 배달", en: "pizza delivery", file: "chef-hat.png", body: "flat vector icon of a flying pizza slice tilted diagonally, yellow #F2C500 triangle with an orange #F59D00 curved crust on the upper right, two red #E94B35 pepperoni circles, small light gray #EBEBEB dashes, and three brown #8D5836 speed lines on the left" },
        { ko: "냄비", en: "pot", file: "dish.png", body: "flat vector icon of a cooking pot, front view, lime green #8BC02F body, deep green #42A141 domed lid with a T-shaped knob handle, and deep green #42A141 curved side handles on both edges" },
        { ko: "푸딩", en: "pudding", file: "soda.png", body: "flat vector icon of a caramel pudding, tan #BF9760 flan body with a yellow #F2C500 caramel layer dripping down in rounded drips, an orange #F59D00 cherry with curved stem on top, and a light gray #EBEBEB plate at the base" },
        { ko: "냉장고", en: "refrigerator", file: "menu-list.png", body: "flat vector icon of an upright refrigerator, lime green #8BC02F upper door and deep green #42A141 lower door, two light gray #EBEBEB horizontal handles on the right edge, and two short deep green #42A141 feet at the bottom" },
        { ko: "밥그릇", en: "rice bowl", file: "apron.png", body: "flat vector icon of a rice bowl, front view, wide yellow #F2C500 bowl with an orange #F59D00 footed base, topped by a puffy light gray #EBEBEB cloud-shaped mound of rice" },
        { ko: "밀대", en: "rolling pin", file: "rolling-pin.png", body: "flat vector icon of a rolling pin tilted diagonally, thick brown #8D5836 rounded cylinder body with tan #BF9760 stub handles protruding from both ends, lower left and upper right" },
        { ko: "간판", en: "sign", file: "food-delivery.png", body: "flat vector icon of a hanging signboard, blank cyan blue #05A9E3 rounded rectangle panel suspended by two light gray #EBEBEB strings meeting in a triangle at a cyan blue #05A9E3 circular ring at the top" },
        { ko: "소다", en: "soda", file: "pizza-cutter.png", body: "flat vector icon of a soda cup, front view, cyan blue #05A9E3 tapered cup with a light gray #EBEBEB lid and a wide light gray #EBEBEB horizontal stripe across the middle, and a cyan blue #05A9E3 bent straw sticking out the top" },
        { ko: "뒤집개", en: "spatula", file: "food-order.png", body: "flat vector icon of a kitchen spatula tilted diagonally, square light gray #EBEBEB flipper head in the upper right with two mid gray #BEBEBE diagonal slots, a mid gray #BEBEBE shaft, and a cyan blue #05A9E3 rounded handle in the lower left" },
        { ko: "수저 세트", en: "spoon and fork", file: "donuts.png", body: "flat vector icon of a fork and spoon standing upright side by side, fork on the left and spoon on the right, light gray #EBEBEB heads and thick rounded cyan blue #05A9E3 handles" },
        { ko: "식탁", en: "table", file: "burger.png", body: "flat vector icon of a dining table draped with a cyan blue #05A9E3 tablecloth, wide rounded silhouette with a scalloped draped bottom edge, and two light gray #EBEBEB legs showing beneath the corners" },
        { ko: "테이크아웃", en: "take away", file: "spoon-and-fork.png", body: "flat vector icon of a take-away paper bag, front view, lime green #8BC02F bag body with a deep green #42A141 folded top flap, and a white cloche-on-tray mark centered on the front" }
      ]
    }
  ]
};
